# Kubernetes Manifest file to create a Hyperledger core-vm-endpoint endpoint
# Date : 28-10-2016
# Version 0.3
# Author : James Buckett (james.buckett@au1.ibm.com)
# Commissioned by ANZ Bank under direction of Ben Smillie (Ben.Smillie@anz.com)

apiVersion: v1
kind: Endpoints

metadata:
  # Hyperledger Validating Peer Service Definition 
  name: svc-core-vm-endpoint
  namespace: hyperledger-06

subsets: 
- addresses:
# Change the IP to the value of interface ens4 on host : core-vm-endpoint
  - ip: 10.140.0.6
  ports: 
  - name: docker-port
    port: 2375
    protocol: TCP
